Randomness in computer science is the ability to generate values or make choices that lack a predictable pattern. 
Because computers are strictly deterministic and follow fixed rules, true physical randomness (like quantum noise) is hard to simulate. 
Instead, computers rely on pseudo-randomness.

Why is Randomness Important?

Cybersecurity: Used to create unpredictable encryption keys, passwords, and secure tokens so malicious actors cannot easily replicate them.
Simulations: Used to model unpredictable events, such as network traffic, climate patterns, or financial markets.
Machine Learning & AI: Ensures unbiased data sampling and breaks up repeating patterns to help models generalize better.
Algorithms: Speeds up processes by skipping through possible solutions randomly (e.g., randomized sorting or testing for prime numbers).
Gaming: Introduces variety, dynamic enemy behaviors, and procedural world generation.

RANDOMNESS IN PYTHON
Python handles randomness primarily through its built-in random module.

Python uses an algorithm called the Mersenne Twister. 
It starts with an initial value (called a seed) and passes it through a complex mathematical formula to generate a number that appears random. 
The seed is typically generated by default using the system's clock

